# To install torch_scatter
# mamba install pytorch-scatter=2.1.2=py311_torch_2.1.0_cu118 -c pyg -c conda-forge -c pytorch -c cuda -c nvidia

name: zap
channels:
- conda-forge
- mosek
- pytorch
- nvidia
- pyg
dependencies:
- cvxpy
- marimo
- matplotlib
- mkl
- mosek::mosek
- numpy
- poetry
- pypsa
- pytest
- python=3.11
- seaborn
- setuptools
- conda-forge::sparse_dot_mkl
- torchvision
- wandb
- conda-forge::cuda-toolkit=11.1
- pytorch::pytorch=2.1.2
- pytorch-scatter=2.1.2=py311_torch_2.1.0_cu118
