name: zap
channels:
- conda-forge
- mosek
- pytorch
dependencies:
- cvxpy
- marimo
- matplotlib
- mkl
- mosek::mosek
- numpy
- poetry
- pypsa
- pytest
- python=3.11
- pytorch
- seaborn
- setuptools
- conda-forge::sparse_dot_mkl
- torchvision
