[tool.poetry]
name = "zap"
version = "0.1.0"
description = "Differentiable electricity models"
authors = ["degleris1 <degleris1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
cvxpy = "^1.4.2"
numpy = "^1.26.4"
scipy = "^1.12.0"
pypsa = {version = "^0.27.0", optional = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
